### ISSUE TITLE
Being able to exit holodeck without python side running

### ISSUE THREAD

**Issue by MaxRobinsonTheGreat** [BYU-PCCL/holodeck#213] opened 2019-05-06 23:20 UTC
It would be nice to be able to exit the holodeck executable without client side running. Originally opened by @nickwalton  /BYU-PCCL/holodeck-engine#84

**Comment by jaydenmilne** [comment] 2020-01-09 19:54
Duplicate of #18

**Closed by jaydenmilne** 2020-01-09 19:54 UTC
Labels: enhancement
