### ISSUE TITLE
Entire Test Suite Cannot Be Run on Docker

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#407] opened 2020-03-27 21:35 UTC
**Describe the bug**
When you try and run the tests in a Docker container, it will eventually crash because there are too many files open.

**To Reproduce**
Run all of the tests in a Docker container. You can run individual tests and modules but not all of them.

**Comment by vinhowe** [comment] 2020-04-07 18:13
Related to #356

**Comment by daniekpo** [comment] 2020-04-13 21:45
Might also be related to #414. I could not reproduce #414 but I think they might be related

**Comment by daniekpo** [comment] 2020-05-11 20:46
Resolved in #418

**Closed by daniekpo** 2020-05-11 20:46 UTC
Labels: bug
