### ISSUE TITLE
Starting unreal engine 4 editor example causes error. [holodeck-engine]

### ISSUE THREAD

**Issue by insooneelife** [BYU-PCCL/holodeck#344] opened 2019-11-13 07:18 UTC
**Describe the bug**

Starting unreal engine 4 editor example causes error. (File not found)
https://github.com/BYU-PCCL/holodeck/blob/master/example.py

At this code, if I start with "editor_example()",
I get error like this.
![image](https://user-images.githubusercontent.com/8437769/68741432-f5304680-0630-11ea-8590-70deab82b4e5.png)

**To Reproduce**
Please provide sample code to reproduce the bug.
Start holodeck with "editor_example()" in "example.py".

**Expected behavior**

**Screenshots**

**Version Information:**
Window10
UE4 4.22
 - Holodeck Version
 - World/Scenario version

**Additional context**

**Comment by jaydenmilne** [comment] 2019-11-19 17:07
I can't read the error message - is this a duplicate of #285?

**Comment by daniekpo** [comment] 2019-11-29 16:39
Did you clone the repo? If so, you need to install the package dependencies using pip. Make sure the following packages are installed:
- pywin32
- numpy
- opencv-python

**Comment by daniekpo** [comment] 2019-12-05 18:15
@insooneelife were you able to resolve this issue? Did the suggested fix work?

**Comment by jaydenmilne** [comment] 2020-01-09 15:54
We can't fix it if we can't read the error mesage

**Closed by jaydenmilne** 2020-01-09 15:54 UTC
Labels: bug
