### ISSUE TITLE
Expose ActionSpace low high members

### ISSUE THREAD

**Issue by kolbytn** [BYU-PCCL/holodeck#332] opened 2019-11-02 17:45 UTC
Public properties exposing the low and high attributes of an Action space.

These values are currently hard coded into the agent class definitions, and there is no way to legitimately access them from a holodeck environment. They should be accessible somehow, and the action space seems like the most intuitive location.

**Comment by MaxRobinsonTheGreat** [comment] 2020-04-07 17:41
Duplicate of #369?

**Comment by kolbytn** [comment] 2020-04-07 17:44
Or rather I think the other was a duplicate of this one. Either way, should be closed.

**Closed** 2020-04-07 17:44 UTC
Labels: enhancement
